spring:
    alarm-log:
        warn:
            mail:
                enabled: false
                smtpHost: xxx
                smtpPort: xxx
                to: xxx
                from: xxx
                username: xxx
                password: xxx
            workweixin:
                enabled: false
                to: xxx,xxx
                applicationId: xxx
                corpid: xxx
                corpsecret: xxx
            dingtalk:
                enabled: false
                token: xxx
                secret: xxx
        warn-exception-extend: false
        simple-warn-info: false
        print-stack-trace: true
        do-warn-exception:
            - java.lang.Throwable
server:
    port: 8191
